// <auto-generated />
using LePhamTheVu_231220962_de01.Models.ComputerDBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LePhamTheVu_231220962_de01.Migrations
{
    [DbContext(typeof(lptvComputerDbContext))]
    [Migration("20251024020947_lptv_v4")]
    partial class lptv_v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LePhamTheVu_231220962_de01.Models.lptvComputer", b =>
                {
                    b.Property<string>("LePhamTheVuComId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LePhamTheVuComImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LePhamTheVuComName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LePhamTheVuComPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LePhamTheVuComStatus")
                        .HasColumnType("bit");

                    b.HasKey("LePhamTheVuComId");

                    b.ToTable("lptvComputer");
                });
#pragma warning restore 612, 618
        }
    }
}
